### ISSUE TITLE
Cluster Creartion Failed

### ISSUE THREAD

**Issue by hemanthavs** [kubernetes-sigs/cluster-api-provider-ibmcloud#148] opened 2019-05-16 17:39 UTC
/kind bug
/sig ibmcloud

**What steps did you take and what happened:**
clusterctl create cluster ...

**What did you expect to happen:**
Successful Creation of Cluster

**Logs from controller-manager**
[controller-manager.log](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/files/3188307/controller-manager.log)

**Environment:**

- Cluster-api version:  
- KIND version: 0.2.1
- Kubernetes version: (use `kubectl version`): v1.13.0
- OS (e.g. from `/etc/os-release`): Ubuntu

**Comment by jichenjc** [comment] 2019-05-17 01:18
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10d6b62]

indicated some nil pointer access, do you have the yaml files under examples/out can be shared? I guess some edge case triggered by your yaml file.. @hemanthavs

**Comment by hemanthavs** [comment] 2019-05-17 01:30
Sure @jichenjc 

[cluster copy yaml.txt](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/files/3189548/cluster.copy.yaml.txt)
[machines copy yaml.txt](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/files/3189549/machines.copy.yaml.txt)

Let me know if you need any more info

**Comment by jichenjc** [comment] 2019-05-17 02:24
I compared this without the yaml file I used and it's similar, so I think yaml files are fine
then because I am able to create with my yaml file, can you confirm the image you used is up to date?

**Comment by xunpan** [comment] 2019-05-17 02:35
There has code error for related case, I will fix it and then you can have a try. @hemanthavs

**Comment by xunpan** [comment] 2019-05-17 02:45
@hemanthavs 

After code merged, you can have a try. And just want to confirm: `cluster-api-provider-ibmcloud` is created in IBM cloud as ssh key name.

**Comment by jichenjc** [comment] 2019-05-17 02:49
@xunpan just to confirm, this is timing issue ? the getIP called before guest ready? or something else?
otherwise, the guest still create failed, but with your PR, it will only log an error instead of panic?

**Comment by xunpan** [comment] 2019-05-17 15:16
`getIP` is called after VM instance is created.  After the PR, the `Create` wil failed with message and should have another try. 

It is not full log and I also not reproduced the issue locally. So, it is hard to say the reason why it fails. Let's check the log if the issue still exists in another try.

**Comment by hemanthavs** [comment] 2019-05-17 23:06
With the Latest Code, Cluster creation is successful. I tested 3 times and creation is successful all the times

**Comment by xunpan** [comment] 2019-05-19 13:40
@hemanthavs 
It's glad to hear that. If it is ok, could you mind to close this ticket?

**Closed** 2019-05-19 13:55 UTC
Labels: kind/bug, sig/ibmcloud
